spring.application.name=SCdeEdeC

# Configuración de la base de datos
spring.datasource.url=jdbc:mysql://195.35.59.3:3306/u484426513_disenocompc226?useSSL=false&serverTimeZone=UTC
spring.datasource.username=u484426513_disenocompc226
spring.datasource.password=S2u4uo#d;70+

# JPA Configuración
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML