<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.example</groupId>
        <artifactId>SCdeEdeC</artifactId>
        <version>0.0.1-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>scdeedec-reparaciones</artifactId>
    <packaging>jar</packaging>

    <name>SCdeEdeC Reparaciones</name>
    <description>Componente de Gestión de Reparaciones</description>

    <dependencies>
        <dependency>
            <groupId>org.example</groupId>
            <artifactId>scdeedec-common</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.example</groupId>
            <artifactId>scdeedec-equipos</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.example</groupId>
            <artifactId>scdeedec-usuarios</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>

    <build>
        <finalName>scdeedec-reparaciones</finalName>
    </build>

</project>